name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Directory
      uses: "jcblw/bash@master"
      args: "bash ls"
    - name: Build and Deploy Docker
      uses: pangzineng/Github-Action-One-Click-Docker@v1.1.1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
